name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request: null
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: 'docker build -t my-app:latest .

        '
      timeout-minutes: 10
    - name: Run Docker container
      run: 'docker run --name my-running-app -d my-app:latest

        '
      timeout-minutes: 5
    - name: Verify container is running
      run: "if [ \"$(docker inspect -f '{{.State.Running}}' my-running-app)\" != \"\
        true\" ]; then\n  echo \"Container is not running!\"\n  exit 1\nfi\n"
    - name: Clean up
      if: always()
      run: 'docker stop my-running-app

        docker rm my-running-app

        docker rmi my-app:latest'
