name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: 'docker build -t myapp:latest .

        '
    - name: Run Docker container
      run: 'docker run --rm myapp:latest

        '
    - name: Cleanup Docker
      if: always()
      run: 'docker system prune -f

        docker rmi myapp:latest'
