name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: 'docker build -t myapp:latest .

        '
      timeout-minutes: 10
    - name: Run Docker Container
      run: 'docker run --rm myapp:latest

        '
      timeout-minutes: 5
    - name: Post-job Cleanup
      if: always()
      run: docker system prune -f
      timeout-minutes: 2
