name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  IMAGE_NAME: my-app
  CONTAINER_NAME: my-app-container
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .
    - name: Run Docker container
      run: docker run -d --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}
    - name: Verify container is running
      run: docker ps | grep ${{ env.CONTAINER_NAME }}
      continue-on-error: true
    - name: Check container logs
      if: failure()
      run: docker logs ${{ env.CONTAINER_NAME }}
