name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  DOCKER_IMAGE: my-app:latest
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker image
      id: docker_build
      run: docker build -t ${{ env.DOCKER_IMAGE }} .
      timeout-minutes: 10
      continue-on-error: false
    - name: Run Docker container
      if: steps.docker_build.outputs.outcome == 'success'
      run: docker run --rm ${{ env.DOCKER_IMAGE }}
      timeout-minutes: 5
      continue-on-error: false
