name: Containerize and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker container
      run: docker build -t my-app .

    - name: Run tests inside container
      run: docker run my-app ./run-tests.sh