name: Containerize and Run

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker container
      run: docker build -t my-container .

    - name: Run Docker container
      run: docker run my-container

    - name: Monitor workflow
      run: echo Monitoring workflow...