name: Containerize and Run
true:
- push
- pull_request
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build -t my-app:latest .
    - name: Run the Docker container
      run: docker run my-app:latest
    - name: Monitor the workflow
      uses: actions/github-script@v3
      with:
        script: "const run_id = process.env.GITHUB_RUN_ID;\nconst { data: run } =\
          \ await github.actions.getWorkflowRun({\n  owner: context.repo.owner,\n\
          \  repo: context.repo.repo,\n  run_id,\n});\nconsole.log(`Workflow ${run.name}\
          \ is ${run.status}`);"
