name: Containerize and Run
true:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
env:
  IMAGE_NAME: my-app
  IMAGE_TAG: latest
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: 'docker build -t $IMAGE_NAME:$IMAGE_TAG .

        '
      timeout-minutes: 5
    - name: Run the Docker container
      run: 'docker run -d --name my-running-app $IMAGE_NAME:$IMAGE_TAG

        '
      timeout-minutes: 5
    - name: Check if container is running
      run: "if [ $(docker ps -q -f name=my-running-app) ]; then\n  echo \"Container\
        \ is running\"\nelse\n  echo \"Container failed to start\" && exit 1\nfi\n"
    - name: Clean up
      if: always()
      run: 'docker stop my-running-app || true

        docker rm my-running-app || true

        docker rmi $IMAGE_NAME:$IMAGE_TAG || true'
