name: Containerize and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run Docker container
      run: docker run -d --name my-running-app my-app

    - name: Monitor Docker container
      run: docker ps -a
